services:
#  pictures_service:
#    image: pictures_service:v0.4
#    ports:
#      - "5050:5050"
#    volumes:
#      - pictures_service:/var/lib/pictures_service/data

  postgresql:
    image: postgres:16
    ports:
      - "5431:5432"
    environment:
      POSTGRES_DB: hackathon
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgresql:/var/lib/postgresql/data
    networks:
      - backend

  liquibase-migrations:
    image: liquibase/liquibase:4.25
    depends_on:
      - postgresql
    command:
      - --changelog-file=master.xml
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://postgresql:5432/hackathon
      - --username=postgres
      - --password=postgres
      - update
    volumes:
      - ./migrations:/liquibase/changelog
    networks:
      - backend


volumes:
  postgresql: { }
  pictures_service: { }

networks:
  backend: { }
